[package]
name = "arythemetic_expressions_parser_Kharchenko"
version = "0.1.3"
edition = "2024"
license = "MIT"
description = "My own parser for Rust course in KMA that parses simple arythemetic expressions"

[dependencies]
anyhow = "1.0.100"
peg = "0.8.5"
thiserror = "2.0.17"
